# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake g++
          # GTest kaynak olarak geliyor, derlememiz lazım
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build
        run: make all BUILD_WITH_CUDA=0

      - name: Build tests
        run: make test BUILD_WITH_CUDA=0

      - name: Run tests
        run: ./bin/test
