# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Build
        run: make BUILD_WITH_CUDA=0

      - name: Build tests
        run: make test BUILD_WITH_CUDA=0

      - name: Run tests
        run: ./bin/test
